### PR TITLE
Add lab 4-5

### PR DESCRIPTION
**Pull request by saba024**

### CODE REVIEW

**Comment by saba024** [comment]
Add full project. To see the template login with login = Bob; password = admin; If the error 405 will occur reload page.

**Review by gmltA — CHANGES_REQUESTED** [review]
I just created a new profile and already see some transactions there. How's that?
___

image

I'll see all users here? I can't deselect the user.
___

And the app doesn't work for me properly.

image
Header is gone.

No mobile version

**Comment by saba024** [comment]
I added groups so now after signing up you will not see the transactions and debts. To add transaction you will need to add at least one member. I replace radio box with checkbox so now members can be easily disabled. I also add mobile version

**Review by gmltA — APPROVED** [review]
Okay. The resulting mark is <kbd>6</kbd>.

Good luck.

**Comment by saba024** [comment]
Thank you

**Pull request merged**
